apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-proxy
  labels:
    app: md-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md-proxy
  template:
    metadata:
      labels:
        app: md-proxy
    spec:
      imagePullSecrets:
        - name: registry-1
      containers:
        - name: md-proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          ports:
            - name: http-port
              containerPort: {{ .Values.proxy.env.PORT }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.proxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl4ai
  labels:
    app: crawl4ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawl4ai
  template:
    metadata:
      labels:
        app: crawl4ai
    spec:
      containers:
        - name: crawl4ai
          image: "{{ .Values.crawl.image.repository }}:{{ .Values.crawl.image.tag }}"
          ports:
            - name: http-port
              containerPort: {{ .Values.crawl.port }}
              protocol: TCP